### ISSUE TITLE
Unable to start EMDriver 

### ISSUE THREAD

**Issue by vikasprasadste** [WebFuzzing/rest-api-example#1]
Hi @arcuri82 , I am trying to start EMDriver and bump into below error.

JRE in build path is 1.8.

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:244)
	at shaded.com.ea.agentloader.AgentLoader.loadAgent(AgentLoader.java:77)
	at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:148)
	at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:102)
	at org.evomaster.client.java.controller.InstrumentedSutStarter.<init>(InstrumentedSutStarter.java:42)
	at org.example.EMDriver.main(EMDriver.java:24)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:240)
	... 5 more
Caused by: java.lang.RuntimeException: This jre doesn't support the native library for attaching to the jvm
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:109)
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:56)
	... 10 more
Caused by: java.lang.UnsatisfiedLinkError: sun.tools.attach.WindowsVirtualMachine.init()V
	at sun.tools.attach.WindowsVirtualMachine.init(Native Method)
	at sun.tools.attach.WindowsVirtualMachine.<clinit>(WindowsVirtualMachine.java:192)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:104)
	... 11 more

**Comment by arcuri82** [comment]
Hi,

 should use a JDK, not a JRE

**Comment by agrawalhemant5393** [comment]
I am getting the similar issue and using JDK only.

**Comment by arcuri82** [comment]
@agrawalhemant5393 you are getting a `java.lang.RuntimeException: This jre doesn't support the native library for attaching to the jvm`  while running with JDK 8?

**Comment by agrawalhemant5393** [comment]
@arcuri82 I am getting this one
```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:244)
	at shaded.com.ea.agentloader.AgentLoader.loadAgent(AgentLoader.java:77)
	at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:148)
	at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:102)
	at org.evomaster.client.java.controller.InstrumentedSutStarter.loadAgent(InstrumentedSutStarter.java:37)
	at org.evomaster.client.java.controller.InstrumentedSutStarter.<init>(InstrumentedSutStarter.java:46)
	at org.example.EMDriver.main(EMDriver.java:27)
Caused by: java.lang.reflect.InvocationTargetException ```

**Comment by arcuri82** [comment]
@agrawalhemant5393  can you please provide the full stack-trace of the error?

**Comment by agrawalhemant5393** [comment]
``` 
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:244)
	at shaded.com.ea.agentloader.AgentLoader.loadAgent(AgentLoader.java:77)
	at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:148)
	at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:102)
	at org.evomaster.client.java.controller.InstrumentedSutStarter.loadAgent(InstrumentedSutStarter.java:37)
	at org.evomaster.client.java.controller.InstrumentedSutStarter.<init>(InstrumentedSutStarter.java:46)
	at org.example.EMDriver.main(EMDriver.java:27)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:240)
	... 6 more
Caused by: java.lang.RuntimeException: java.io.IOException: Can not attach to current VM
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:90)
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:56)
	... 11 more
Caused by: java.io.IOException: Can not attach to current VM
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.<init>(HotSpotVirtualMachine.java:76)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:48)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:69)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:86)
	... 12 more
```

I am using Eclipse and exactly same code that you shared.

**Comment by arcuri82** [comment]
`java.io.IOException: Can not attach to current VM` are you using JDK 8? If not, then that error is expected (but I guess we could give a more descriptive error message).

**Comment by arcuri82** [comment]
if you are running your own app with JDK above 8 (and __NOT__ this `rest-api-example`), then you need to read the [documentation](https://github.com/EMResearch/EvoMaster/blob/master/docs/jdks.md)

**Comment by agrawalhemant5393** [comment]
I am currently running your given code with JDK 8 itself. @arcuri82 . Still I will check the document and try to clear the issue. Kindly check it from your side if anything you can help with. 

Thanks

**Comment by agrawalhemant5393** [comment]
Is there any specific version of JAVA 8? @arcuri82

**Comment by arcuri82** [comment]
no, there is no specific version of JDK 8. what do you get if you run:
```
 java -version
```
?

**Comment by agrawalhemant5393** [comment]
Hi @arcuri82 
I am using this version:

```
java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)
```

**Comment by arcuri82** [comment]
do u get the same error if you run with JVM option `-Djdk.attach.allowAttachSelf=true` ?

**Comment by agrawalhemant5393** [comment]
Getting this after running with the above command:
```
Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:513)
Caused by: java.lang.ExceptionInInitializerError
	at org.evomaster.client.java.instrumentation.InstrumentingAgent.agentmain(InstrumentingAgent.java:62)
	... 6 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @bf17582
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.evomaster.client.java.instrumentation.InstrumentingAgent$TransformerForTests.<clinit>(InstrumentingAgent.java:121)
	... 7 more
Agent failed to start!
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:244)
	at shaded.com.ea.agentloader.AgentLoader.loadAgent(AgentLoader.java:77)
	at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:148)
	at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:102)
	at org.evomaster.client.java.controller.InstrumentedSutStarter.loadAgent(InstrumentedSutStarter.java:37)
	at org.evomaster.client.java.controller.InstrumentedSutStarter.<init>(InstrumentedSutStarter.java:46)
	at org.example.EMDriver.main(EMDriver.java:27)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:240)
	... 6 more
Caused by: java.lang.RuntimeException: Can't attach to this jvm. Add -javaagent:C:\Users\hemanta\AppData\Local\Temp\javaagent.org.evomaster.client.java.instrumentation.InstrumentingAgent3290040186493212250.jar to the commandline
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:74)
	... 11 more
Caused by: com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:166)
	at shaded.com.ea.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:65)
	... 11 more
	```

**Comment by arcuri82** [comment]
`accessible: module java.base does not "opens java.lang" to unnamed module`  that's JDK 9+ stuff... are you sure that from Eclipse you are using JDK 8 and not another version? do u have any other JDK version installed on your machine?

**Comment by agrawalhemant5393** [comment]
No other JDK installed in my system. As of now, I only jdk 8
![image](https://user-images.githubusercontent.com/39014040/198282908-cc05ea9d-583c-485b-bea5-ee57bb2461df.png)
![image](https://user-images.githubusercontent.com/39014040/198283005-e535e32b-124c-4edc-9f6c-806e4c7c6d5b.png)
![image](https://user-images.githubusercontent.com/39014040/198283421-c86ec993-f5f8-4451-8dbe-bf5e161f6e1a.png)


You can check the image.

**Comment by arcuri82** [comment]
that is very weird... might be an Eclipse issue (eg using an internal JDK >=9 to run).
can you try to open such project with IntelliJ Community Edition?

**Comment by agrawalhemant5393** [comment]
Okay I will try that. I am currently reinstalling everything like Java Eclipse and whole system and then I will update. I think you are right it must be Eclipse issue. @arcuri82  Thanks. I will update you soon on the same.

**Comment by agrawalhemant5393** [comment]
Hi @arcuri82 It was the eclipse issue. It was taking some latest version while executing. I downgraded the version and tried. It works.
